[package]
name = "mawang-projekt-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "*"
tokio = {version = "*", features = ["full"]}
maud = "*"

[profile.dev]
opt-level = "s"
debug = false
debug-assertions = false
strip = "debuginfo"
incremental = false
